version: "3"
services:
  app:
    container_name: aud_io
    restart: always
    build: . #tells docker to use Dockerfile
    ports:
      - "80:4000"
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./db_backup:/db_backup
    ports:
      - "27017:27017"
