version: "3"
services:
  app:
    container_name: aud_io
    restart: always
    build: . #tells docker to use Dockerfile
    ports:
      - "80:3000"
      - "4000:4000"
    volumes:
      - ./:/app/
    depends_on:
      - mongo
    command: ["npm", "run", "dev"]
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./db_backup:/db_backup
    ports:
      - "27017:27017"
    command:
      - "mongorestore --db aud_io db_backup/"

volumes:
  node_modules:
