/////// USER

enum ActionTypes {
  CLEAR_ERROR_MSG = "CLEAR_ERROR_MSG",
  LOGIN_USER_INIT = "LOGIN_USER_INIT",
  LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS",
  LOGIN_USER_FAIL = "LOGIN_USER_FAIL",

  USER_AUTH_INIT = "USER_AUTH_INIT",
  USER_AUTH_SUCCESS = "USER_AUTH_SUCCESS",
  USER_AUTH_FAIL = "USER_AUTH_FAIL",

  LOGOUT_USER_INIT = "LOGOUT_USER_INIT",
  LOGOUT_USER_SUCCESS = "LOGOUT_USER_SUCCESS",

  USER_UPDATE_INIT = "USER_UPDATE_INIT",
  USER_UPDATE_SUCCESS = "USER_UPDATE_SUCCESS",

  USER_SIGNUP_INIT = "USER_SIGNUP_INIT",
  USER_SIGNUP_SUCCESS = "USER_SIGNUP_SUCCESS",
  USER_SIGNUP_FAIL = "USER_SIGNUP_FAIL",

  PROFILE_DATA_INIT = "PROFILE_DATA_INIT",
  PROFILE_DATA_SUCCESS = "PROFILE_DATA_SUCCESS",
  PROFILE_DATA_FAIL = "PROFILE_DATA_FAIL",

  SEARCHBOX_TOUCHED = "SEARCHBOX_TOUCHED",
  SEARCHBOX_KEYPRESS = "SEARCHBOX_KEYPRESS",
  SEARCHBOX_CLEAR = "SEARCHBOX_CLEAR",
  SEARCH_USERS_SUCCESS = "SEARCH_USERS_SUCCESS",

  GET_USERS_INIT = "GET_USERS_INIT",
  GET_USERS_SUCCESS = "GET_USERS_SUCCESS",

  CLEAR_PROFILE_DATA = "CLEAR_PROFILE_DATA"
}

export default ActionTypes;
