/////// USER 

export const CLEAR_ERROR_MSG = 'CLEAR_ERROR_MSG';

export const LOGIN_USER_INIT = 'LOGIN_USER_INIT';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_FAIL = 'LOGIN_USER_FAIL';

export const USER_AUTH_INIT = 'USER_AUTH_INIT';
export const USER_AUTH_SUCCESS = 'USER_AUTH_SUCCESS';
export const USER_AUTH_FAIL = 'USER_AUTH_FAIL';

export const LOGOUT_USER_INIT = 'LOGOUT_USER_INIT';
export const LOGOUT_USER_SUCCESS = 'LOGOUT_USER_SUCCESS';

export const USER_UPDATE_INIT = 'USER_UPDATE_INIT';
export const USER_UPDATE_SUCCESS = 'USER_UPDATE_SUCCESS';

export const USER_SIGNUP_INIT = 'USER_SIGNUP_INIT'
export const USER_SIGNUP_SUCCESS = 'USER_SIGNUP_SUCCESS'
export const USER_SIGNUP_FAIL = 'USER_SIGNUP_FAIL'

export const PROFILE_DATA_INIT = 'PROFILE_DATA_INIT';
export const PROFILE_DATA_SUCCESS = 'PROFILE_DATA_SUCCESS';
export const PROFILE_DATA_FAIL = 'PROFILE_DATA_FAIL';

export const SEARCHBOX_TOUCHED = 'SEARCHBOX_TOUCHED';
export const SEARCHBOX_KEYPRESS = 'SEARCHBOX_KEYPRESS';
export const SEARCHBOX_CLEAR = 'SEARCHBOX_CLEAR';
export const SEARCH_USERS_SUCCESS = 'SEARCH_USERS_SUCCESS';

export const GET_USERS_INIT = 'GET_USERS_INIT';
export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS';

export const CLEAR_PROFILE_DATA = 'CLEAR_PROFILE_DATA';