export const CLEAR_ERROR_MSG = 'CLEAR_ERROR_MSG';

export const LOGIN_USER_INIT = 'LOGIN_USER_INIT';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_FAIL = 'LOGIN_USER_FAIL';

export const USER_AUTH_INIT = 'USER_AUTH_INIT';
export const USER_AUTH_SUCCESS = 'USER_AUTH_SUCCESS';
export const USER_AUTH_FAIL = 'USER_AUTH_FAIL';

export const LOGOUT_USER_INIT = 'LOGOUT_USER_INIT';
export const LOGOUT_USER_SUCCESS = 'LOGOUT_USER_SUCCESS';

export const USER_UPDATE_INIT = 'USER_UPDATE_INIT';
export const USER_UPDATE_SUCCESS = 'USER_UPDATE_SUCCESS';

export const USER_SIGNUP_INIT = 'USER_SIGNUP_INIT'
export const USER_SIGNUP_SUCCESS = 'USER_SIGNUP_SUCCESS'
export const USER_SIGNUP_FAIL = 'USER_SIGNUP_FAIL'

export const PROFILE_DATA_INIT = 'PROFILE_DATA_INIT';
export const PROFILE_DATA_SUCCESS = 'PROFILE_DATA_SUCCESS';
export const PROFILE_DATA_FAIL = 'PROFILE_DATA_FAIL';